name-template: "MediTrack Diabetes v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: " Features"
    labels: [feature, enhancement]
  - title: " Fixes"
    labels: [bug, fix]
  - title: " Chores"
    labels: [chore, infra, deps]
  - title: " Tests"
    labels: [test]
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
template: |
  ## Changes
  $CHANGES

  ## Notes
  - Built from: $COMMIT
  - Compare: $COMPARE_URL
