name: ci
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install deps
        run: pnpm i
      - name: Typecheck
        run: pnpm -r run typecheck
      - name: Lint
        run: pnpm -r run lint
      - name: Build web dashboard (optional)
        run: pnpm --filter web-dashboard build || true

