name: ci
on:
  push:
    branches: [main, work]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps
        run: pnpm i
      - name: Typecheck (if configured)
        run: pnpm -r run typecheck || true
      - name: Lint (if configured)
        run: pnpm -r run lint || true
      - name: Build web dashboard (optional)
        run: pnpm --filter web-dashboard build || true
