name: deploy-functions
on:
  push:
    branches: [ main ]
    paths:
      - "supabase/functions/**"
      - ".github/workflows/deploy-functions.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Supabase login
        run: supabase login --token "${{ secrets.SUPABASE_ACCESS_TOKEN }}"
      - name: Deploy send-refill-email
        working-directory: ./supabase
        run: supabase functions deploy send-refill-email --project-ref "${{ secrets.SUPABASE_PROJECT_REF }}"
      - name: Deploy send-low-stock-push
        working-directory: ./supabase
        run: supabase functions deploy send-low-stock-push --project-ref "${{ secrets.SUPABASE_PROJECT_REF }}"
